import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hi</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>메인페이지</h1>
        <p
          onClick={() => {
            console.log(process.env.MYSQL_DATABASE);
          }}
        >
          현재 접속중인 schema {process.env.MYSQL_DATABASE}
        </p>
        <p
          onClick={() => {
            console.log(process.env.customKey);
          }}
        >
          next.config.js의 env {process.env.customKey}
        </p>
        <Link href={'/posts/list'}>게시판으로 이동하기</Link>
      </main>
    </>
  );
}
